name: stretch_sim
robot_state:
  joint_state:
    name: [joint_head_tilt, joint_head_pan, joint_wrist_yaw, joint_arm_l0, joint_arm_l1, joint_arm_l2, joint_arm_l3, joint_lift, joint_gripper_finger_left, joint_gripper_finger_right]
    position: [0, 0, 0.0, 0, 0, 0, 0, 0.4, 0, 0]
  robot_model_name: stretch
fixed_frame_transforms:
  - child_frame_id: world
    transform:
      rotation: [0, 0, 0, 1]
      translation: [0, 0, 0]
world:
  collision_objects:
    - id: Bed
      mesh_poses:
        - position: [-0.6, 0, 0] 
          orientation: [0, 0, 0.707, 0.707]
      meshes:
        - dimensions: [0.8, 0.8, 0.8]
          resource: resources/scenes/nursing_env/objects/bed/model.dae 
    - id: human
      mesh_poses:
        - position: [-1.3, -0.25, 1.25]
          orientation: [0, 0, 0.7071, 0.7071]
      meshes:
        - dimensions: [0.85, 0.85, 0.85]
          resource: resources/scenes/nursing_env/objects/doctor1/model.dae
    - id: Doctor2
      mesh_poses:
        - position: [-1.3, 0.2, 0.0017]
          orientation: [0, 0, 0.707, 0.707] 
      meshes:
        - dimensions: [0.75, 0.75, 0.75]
          resource: resources/scenes/nursing_env/objects/doctor2/model.dae
    - id: Curtain1
      mesh_poses:
        - position: [-1.0, -2.5, 0] 
          orientation: [0, 0, 1, 0]
      meshes:
        - dimensions: [1.75, 0.8, 0.6]
          resource: resources/scenes/nursing_env/objects/curtain/model.dae    
    - id: Curtain2
      mesh_poses:
        - position: [-3.65, 0, 0] 
          orientation: [0, 0, 0.707, 0.707]
      meshes:
        - dimensions: [1.75, 0.8, 0.6]
          resource: resources/scenes/nursing_env/objects/curtain/model.dae 
    - id: Curtain3
      mesh_poses:
        - position: [-1.0, 2.5, 0] 
          orientation: [0, 0, 0, 1]
      meshes:
        - dimensions: [1.75, 0.8, 0.6]
          resource: resources/scenes/nursing_env/objects/curtain/model.dae  
    - id: Curtain4
      mesh_poses:
        - position: [1.8, 0, 0] 
          orientation: [0, 0, 0.707, -0.707]
      meshes:
        - dimensions: [1.75, 0.8, 0.6]
          resource: resources/scenes/nursing_env/objects/curtain/model.dae 
    - id: Machine
      mesh_poses:
        - position: [0.9, -1.6, 0] 
          orientation: [0, 0, 0.707, -0.707]
      meshes:
        - dimensions: [0.8, 0.8, 0.8]
          resource: resources/scenes/nursing_env/objects/machine/model.dae 
    - id: Cabinet
      mesh_poses:
        - position: [0.1, 2.1, 0] 
          orientation: [0, 0, 0, 1]
      meshes:
        - dimensions: [0.2, 0.2, 0.2]
          resource: resources/scenes/nursing_env/objects/cabinet/model.dae 
    - id: Drip
      mesh_poses:
        - position: [1.0, 0, 0] 
          orientation: [0, 0, -0.707, 0.707]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/nursing_env/objects/drip/model.dae    
    - id: Chair
      mesh_poses:
        - position: [0.9, 1.4, 0] 
          orientation: [0, 0, -0.707, 0.707]
      meshes:
        - dimensions: [0.1, 0.1, 0.1]
          resource: resources/scenes/nursing_env/objects/chair/model.dae  