name: stretch_sim
robot_state:
  joint_state:
    name: [joint_head_tilt, joint_head_pan, joint_wrist_yaw, joint_arm_l0, joint_arm_l1, joint_arm_l2, joint_arm_l3, joint_lift, joint_gripper_finger_left, joint_gripper_finger_right]
    position: [0, 0, 0.0, 0, 0, 0, 0, 0.4, 0, 0]
  robot_model_name: stretch
fixed_frame_transforms:
  - child_frame_id: world
    transform:
      rotation: [0, 0, 0, 1]
      translation: [0, 0, 0]
world:
  collision_objects:
    - id: human
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [2, 2, 1.65]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/human/model.dae
          render_resource: resources/scenes/environment/objects/human/model.usdz
    - id: sofa
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [-0.462, -1.06, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/sofa/model.dae
    - id: table
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [1.4665000000000001, 0, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/table/model.dae
    - id: chair
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [2.1665, 0, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/chair/model.dae
    - id: cup
      mesh_poses:
        - orientation: [0, 0, 0.7071068, -0.7071068]
          position: [1.4665000000000001, 0, 0.7]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/cup/model.dae
          render_resource: resources/scenes/environment/objects/cup/model.usdz
    - id: monitor
      mesh_poses:
        - orientation: [0, 0, 0.7071068, -0.7071068]
          position: [1.25, 0, 0.9]
      meshes:
        - dimensions: [1, 1, 1]
          resource: resources/scenes/environment/objects/monitor/model.dae
          render_resource: resources/scenes/environment/objects/monitor/model.usdz
    - id: wall_south
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [-0.05, 1.06, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/wall/model.dae
    - id: wall_north_1
      mesh_poses:
        - orientation: [0, 0, 0]
          position: [3.733, 1.06, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/wall/model.dae
    - id: wall_north_2
      mesh_poses:
        - orientation: [0, 0, 0]
          position: [3.733, -1.06, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/wall/model.dae