name: ur5_sim
robot_state:
  joint_state:
    name: [elbow_joint, shoulder_lift_joint, shoulder_pan_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
    position: [0, -1.57, 0, -1.57, 0, 0]
  robot_model_name: ur5
fixed_frame_transforms:
  - child_frame_id: world
    transform:
      rotation: [0, 0, 0, 1]
      translation: [0, 0, 0]
world:
  collision_objects:
    - id: cup
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [0.35, 0.5, 0.7]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/cup/model.obj
          render_resource: resources/scenes/environment/objects/cup/model.usdz
    - id: floor
      primitive_poses:
        - orientation: [0, 0, 0, 1]
          position: [0, 0, -0.02]
      primitives:
        - dimensions: [3.0, 3.0, 0.005]
          type: box
    - id: table
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [0, 0, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/Table/model.obj
          render_resource: resources/scenes/environment/objects/Table/model.usdz
    - id: monitor
      mesh_poses:
        - orientation: [0, 0, -0.7071068, -0.7071068]
          position: [0.25, 0.5, 0.9]
      meshes:
        - dimensions: [1, 1, 1]
          resource: resources/scenes/environment/objects/monitor/model.obj
          render_resource: resources/scenes/environment/objects/monitor/model.usdz