name: ur5_sim
robot_state:
  joint_state:
    name: [elbow_joint, shoulder_lift_joint, shoulder_pan_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
    position: [0, -1.57, 0, -1.57, 0, 0]
  robot_model_name: ur5
fixed_frame_transforms:
  - child_frame_id: world
    transform:
      rotation: [0, 0, 0, 1]
      translation: [0, 0, 0]
world:
  collision_objects:
    # - id: cup
    #   mesh_poses:
    #     - orientation: [0, 0, 0, 1]
    #       position: [0, 0, 0.7]
    #   meshes:
    #     - dimensions: [1.0, 1.0, 1.0]
    #       resource: resources/scenes/environment/objects/cup/model.obj
    #       render_resource: resources/scenes/environment/objects/cup/model.usdz
    - id: table
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [0, 0, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/Table/model.obj
          render_resource: resources/scenes/environment/objects/Table/model.usdz
    - id: monitor
      mesh_poses:
        - orientation: [0, 0, -0.7071068, 0.7071068]
          position: [0, 0, 0.92]
      meshes:
        - dimensions: [1, 1, 1]
          resource: resources/scenes/environment/objects/monitor/model.obj
          render_resource: resources/scenes/environment/objects/monitor/model.usdz
    # - id: wall-right
    #   mesh_poses:
    #     - orientation: [0.7071068, 0, 0, 0.7071068]
    #       position: [0, 1.5, 0]
    #   meshes:
    #     - dimensions: [0.015, 0.006, 0.02]
    #       resource: resources/scenes/environment/objects/wall_new/model.obj
    #       render_resource: resources/scenes/environment/objects/wall_new/model.usdz
    # - id: wall-left
    #   mesh_poses:
    #     - orientation: [0.7071068, 0, 0, 0.7071068]
    #       position: [0, -1.5, 0]
    #   meshes:
    #     - dimensions: [0.015, 0.006, 0.02]
    #       resource: resources/scenes/environment/objects/wall_new/model.obj
    #       render_resource: resources/scenes/environment/objects/wall_new/model.usdz
    - id: wall_right
      mesh_poses:
        - orientation: [0.7071068, 0, 0, 0.7071068]
          position: [0.25, 1.3, 0.6]
      meshes:
        - dimensions: [30, 0.6, 0.1]
          resource: resources/scenes/environment/objects/wall/model.obj
          render_resource: resources/scenes/environment/objects/wall/model.usdz
    - id: wall_left
      mesh_poses:
        - orientation: [0.7071068, 0, 0, 0.7071068]
          position: [0.25, -1.3, 0.6]
      meshes:
        - dimensions: [30, 0.6, 0.1]
          resource: resources/scenes/environment/objects/wall/model.obj
          render_resource: resources/scenes/environment/objects/wall/model.usdz
    - id: wall_bottom_left
      mesh_poses:
        - orientation: [0.5, 0.5, 0.5, 0.5]
          position: [-1.25, -2.55, 0.6]
      meshes:
        - dimensions: [25, 0.6, 0.1]
          resource: resources/scenes/environment/objects/wall/model.obj
          render_resource: resources/scenes/environment/objects/wall/model.usdz
    - id: wall_bottom_right
      mesh_poses:
        - orientation: [0.5, 0.5, 0.5, 0.5]
          position: [-1.25, 2.55, 0.6]
      meshes:
        - dimensions: [25, 0.6, 0.1]
          resource: resources/scenes/environment/objects/wall/model.obj
          render_resource: resources/scenes/environment/objects/wall/model.usdz
    - id: wall_top
      mesh_poses:
        - orientation: [0.5, 0.5, 0.5, 0.5]
          position: [-4.5, 0, 0.6]
      meshes:
        - dimensions: [100, 0.6, 0.1]
          resource: resources/scenes/environment/objects/wall/model.obj
          render_resource: resources/scenes/environment/objects/wall/model.usdz
    - id: chair
      mesh_poses:
        - orientation: [0, 0, 0.7071068, 0.7071068]
          position: [-3.4, 0, 0]
      meshes:
        - dimensions: [1, 1, 0.7]
          resource: resources/scenes/environment/objects/Chair/model.obj
          render_resource: resources/scenes/environment/objects/Chair/model.usdz
    - id: table2
      mesh_poses:
        - orientation: [0, 0, 0, 1]
          position: [-3.1, 0, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/Table/model.obj
          render_resource: resources/scenes/environment/objects/Table/model.usdz
    - id: cabinet
      mesh_poses:
        - orientation: [0, 0, 0.7071068, 0.7071068]
          position: [-2.9, 1.1, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/CabinetWhite/model.obj
          render_resource: resources/scenes/environment/objects/CabinetWhite/model.usdz
    - id: trash_can
      mesh_poses:
        - orientation: [1, 0, 0, 1]
          position: [-2.3, -1.0, 0]
      meshes:
        - dimensions: [0.002, 0.002, 0.002]
          resource: resources/scenes/environment/objects/TrashCan/model.obj
          render_resource: resources/scenes/environment/objects/TrashCan/model.usdz  
    - id: chair_2
      mesh_poses:
        - orientation: [0, 0, -0.3826834, 0.9238795]
          position: [-2.4, 0, 0]
      meshes:
        - dimensions: [1.0, 1.0, 1.0]
          resource: resources/scenes/environment/objects/Chair/model.obj
          render_resource: resources/scenes/environment/objects/Chair/model.usdz